# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73401239a3a2a8e783805485cbf677ca87cea0b3356f3447a58146d9ae2f5ec6b108169a931c7154cc3918efc9fff304c0e43199a25e1b1107dfe84285f4a54e

test:
  secret_key_base: 16a504fc06c87962cf37d512197bf941e34ad48facb28c5e543b365507f457711d6c013a3b75766a57dcceff59b60eb6d7694ccd7dc3c7460ad20b564f06e856

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
